# All constants (categories, taxonomy, etc.)

BOOK_CATEGORIES = {
    "Arts & Humanities": {
        "architecture": "Architecture",
        "art_instruction": "Art Instruction",
        "art_history": "Art History",
        "dance": "Dance",
        "design": "Design",
        "fashion": "Fashion",
        "film": "Film",
        "graphic_design": "Graphic Design",
        "music": "Music",
        "music_theory": "Music Theory",
        "painting": "Painting",
        "photography": "Photography",
        "theatre": "Theatre",
        "film_studies": "Film Studies",
        "visual_arts": "Visual Arts",
        "fashion_design": "Fashion Design",
        "art_criticism": "Art Criticism",
        "philosophy": "Philosophy",
        "literature": "Literature",
        "poetry": "Poetry",
        "creative_writing": "Creative Writing",
        "classical_studies": "Classical Studies",
        "religion": "Religion",
        "mythology": "Mythology",
    },
    "Foreign Languages & Linguistics": {
        "english_language": "English Language",
        "spanish_language": "Spanish Language",
        "french_language": "French Language",
        "german_language": "German Language",
        "chinese_language": "Chinese Language",
        "japanese_language": "Japanese Language",
        "russian_language": "Russian Language",
        "arabic_language": "Arabic Language",
        "italian_language": "Italian Language",
        "portuguese_language": "Portuguese Language",
        "korean_language": "Korean Language",
        "linguistics": "Linguistics",
        "comparative_literature": "Comparative Literature",
        "translation_studies": "Translation Studies",
        "second_language_acquisition": "Second Language Acquisition",
        "Applied_Linguistics": "Applied Linguistics",
    },
    "International Studies & Area Studies": {
        "international_relations": "International Relations",
        "global_studies": "Global Studies",
        "diplomacy": "Diplomacy",
        "development_studies": "Development Studies",
        "human_rights": "Human Rights",
        "peace_and_conflict": "Peace and Conflict Studies",
        "security_studies": "Security Studies",
        "south_asian_studies": "South Asian Studies",
        "east_asian_studies": "East Asian Studies",
        "middle_eastern_studies": "Middle Eastern Studies",
        "african_studies": "African Studies",
        "latin_american_studies": "Latin American Studies",
        "european_studies": "European Studies",
        "diaspora_studies": "Diaspora Studies",
    },
    "Social Sciences": {
        "anthropology": "Anthropology",
        "archaeology": "Archaeology",
        "sociology": "Sociology",
        "psychology": "Psychology",
        "political_science": "Political Science",
        "public_administration": "Public Administration",
        "public_policy": "Public Policy",
        "media_studies": "Media Studies",
        "communication": "Communication",
        "gender_studies": "Gender Studies",
        "cultural_studies": "Cultural Studies",
        "urban_studies": "Urban Studies",
        "education": "Education",
        "criminology": "Criminology",
    },
    "Economics & Business": {
        "economics": "Economics",
        "econometrics": "Econometrics",
        "finance": "Finance",
        "management": "Management",
        "marketing": "Marketing",
        "entrepreneurship": "Entrepreneurship",
        "human_resources": "Human Resources",
        "international_business": "International Business",
        "organizational_behavior": "Organizational Behavior",
        "business_ethics": "Business Ethics",
        "supply_chain_management": "Supply Chain Management",
        "strategic_management": "Strategic Management",
    },
    "Law & Governance": {
        "constitutional_law": "Constitutional Law",
        "international_law": "International Law",
        "human_rights_law": "Human Rights Law",
        "environmental_law": "Environmental Law",
        "corporate_law": "Corporate Law",
        "criminal_law": "Criminal Law",
        "administrative_law": "Administrative Law",
        "tax_law": "Tax Law",
        "maritime_law": "Maritime Law",
    },
    "Engineering & Technology": {
        "computer_science": "Computer Science",
        "programming": "Programming",
        "software_engineering": "Software Engineering",
        "information_technology": "Information Technology",
        "electrical_engineering": "Electrical Engineering",
        "mechanical_engineering": "Mechanical Engineering",
        "civil_engineering": "Civil Engineering",
        "chemical_engineering": "Chemical Engineering",
        "aerospace_engineering": "Aerospace Engineering",
        "biomedical_engineering": "Biomedical Engineering",
        "materials_science": "Materials Science",
        "nanotechnology": "Nanotechnology",
        "robotics": "Robotics",
        "artificial_intelligence": "Artificial Intelligence",
        "machine_learning": "Machine Learning",
        "data_science": "Data Science",
        "cyber_security": "Cyber Security",
        "networking": "Networking",
        "quantum_computing": "Quantum Computing",
        "renewable_energy": "Renewable Energy",
        "environmental_engineering": "Environmental Engineering",
    },
    "Natural & Formal Sciences": {
        "biology": "Biology",
        "biochemistry": "Biochemistry",
        "molecular_biology": "Molecular Biology",
        "ecology": "Ecology",
        "genetics": "Genetics",
        "neuroscience": "Neuroscience",
        "physics": "Physics",
        "chemistry": "Chemistry",
        "mathematics": "Mathematics",
        "statistics": "Statistics",
        "astronomy": "Astronomy",
        "geology": "Geology",
        "environmental_science": "Environmental Science",
        "quantitative_methods": "Quantitative Methods",
        "optimization": "Optimization",
        "operations_research": "Operations Research",
    },
}

ARXIV_TAXONOMY = {
    "Computer Science": {
        'cs.AI':  'Artificial Intelligence',
        'cs.AR':  'Hardware Architecture',
        'cs.CC':  'Computational Complexity',
        'cs.CE':  'Computational Engineering, Finance, and Science',
        'cs.CG':  'Computational Geometry',
        'cs.CL':  'Computation and Language',
        'cs.CR':  'Cryptography and Security',
        'cs.CV':  'Computer Vision and Pattern Recognition',
        'cs.CY':  'Computers and Society',
        'cs.DB':  'Databases',
        'cs.DC':  'Distributed, Parallel, and Cluster Computing',
        'cs.DL':  'Digital Libraries',
        'cs.DM':  'Discrete Mathematics',
        'cs.DS':  'Data Structures and Algorithms',
        'cs.ET':  'Emerging Technologies',
        'cs.FL':  'Formal Languages and Automata Theory',
        'cs.GL':  'General Literature',
        'cs.GR':  'Graphics',
        'cs.GT':  'Computer Science and Game Theory',
        'cs.HC':  'Human-Computer Interaction',
        'cs.IR':  'Information Retrieval',
        'cs.IT':  'Information Theory',
        'cs.LG':  'Machine Learning',
        'cs.LO':  'Logic in Computer Science',
        'cs.MA':  'Multiagent Systems',
        'cs.MM':  'Multimedia',
        'cs.MS':  'Mathematical Software',
        'cs.NA':  'Numerical Analysis',
        'cs.NE':  'Neural and Evolutionary Computing',
        'cs.NI':  'Networking and Internet Architecture',
        'cs.OH':  'Other Computer Science',
        'cs.OS':  'Operating Systems',
        'cs.PF':  'Performance',
        'cs.PL':  'Programming Languages',
        'cs.RO':  'Robotics',
        'cs.SC':  'Symbolic Computation',
        'cs.SD':  'Sound',
        'cs.SE':  'Software Engineering',
        'cs.SI':  'Social and Information Networks',
        'cs.SY':  'Systems and Control',
    },
    "Economics": {
        'econ.EM': 'Econometrics',
        'econ.GN': 'General Economics',
        'econ.TH': 'Theoretical Economics',
    },
    "Electrical Engineering and Systems Science": {
        'eess.AS': 'Audio and Speech Processing',
        'eess.IV': 'Image and Video Processing',
        'eess.SP': 'Signal Processing',
        'eess.SY': 'Systems and Control (eee)',
    },
    "Mathematics": {
        'math.AC': 'Commutative Algebra',
        'math.AG': 'Algebraic Geometry',
        'math.AP': 'Analysis of PDEs',
        'math.AT': 'Algebraic Topology',
        'math.CA': 'Classical Analysis and ODEs',
        'math.CO': 'Combinatorics',
        'math.CT': 'Category Theory',
        'math.CV': 'Complex Variables',
        'math.DG': 'Differential Geometry',
        'math.DS': 'Dynamical Systems',
        'math.FA': 'Functional Analysis',
        'math.GM': 'General Mathematics',
        'math.GN': 'General Topology',
        'math.GR': 'Group Theory',
        'math.GT': 'Geometric Topology',
        'math.HO': 'History and Overview',
        'math.IT': 'Information Theory (math)',
        'math.KT': 'K-Theory and Homology',
        'math.LO': 'Logic',
        'math.MG': 'Metric Geometry',
        'math.MP': 'Mathematical Physics',
        'math.NA': 'Numerical Analysis (math)',
        'math.NT': 'Number Theory',
        'math.OA': 'Operator Algebras',
        'math.OC': 'Optimization and Control',
        'math.PR': 'Probability',
        'math.QA': 'Quantum Algebra',
        'math.RA': 'Rings and Algebras',
        'math.RT': 'Representation Theory',
        'math.SG': 'Symplectic Geometry',
        'math.SP': 'Spectral Theory',
        'math.ST': 'Statistics Theory',
    },
    "Physics": {
        'astro-ph.CO': 'Cosmology and Nongalactic Astrophysics',
        'astro-ph.EP': 'Earth and Planetary Astrophysics',
        'astro-ph.GA': 'Astrophysics of Galaxies',
        'astro-ph.HE': 'High Energy Astrophysical Phenomena',
        'astro-ph.IM': 'Instrumentation and Methods for Astrophysics',
        'astro-ph.SR': 'Solar and Stellar Astrophysics',
        'cond-mat.dis-nn':  'Disordered Systems and Neural Networks',
        'cond-mat.mes-hall': 'Mesoscale and Nanoscale Physics',
        'cond-mat.mtrl-sci': 'Materials Science',
        'cond-mat.other':   'Other Condensed Matter',
        'cond-mat.quant-gas':'Quantum Gases',
        'cond-mat.soft':    'Soft Condensed Matter',
        'cond-mat.stat-mech':'Statistical Mechanics',
        'cond-mat.str-el':  'Strongly Correlated Electrons',
        'cond-mat.supr-con':'Superconductivity',
        'gr-qc': 'General Relativity and Quantum Cosmology',
        'hep-ex': 'High Energy Physics - Experiment',
        'hep-lat':'High Energy Physics - Lattice',
        'hep-ph': 'High Energy Physics - Phenomenology',
        'hep-th':'High Energy Physics - Theory',
        'math-ph': 'Mathematical Physics(Physics)',
        'nlin.AO': 'Adaptation and Self-Organizing Systems',
        'nlin.CD': 'Chaotic Dynamics',
        'nlin.CG': 'Cellular Automata and Lattice Gases',
        'nlin.PS': 'Pattern Formation and Solitons',
        'nlin.SI': 'Exactly Solvable and Integrable Systems',
        'nucl-ex': 'Nuclear Experiment',
        'nucl-th':'Nuclear Theory',
        'physics.bio-ph':       'Biological Physics',
        'physics.chem-ph':      'Chemical Physics',
        'physics.class-ph':     'Classical Physics',
        'physics.comp-ph':      'Computational Physics',
        'physics.data-an':      'Data Analysis, Statistics and Probability',
        'physics.ed-ph':        'Physics Education',
        'physics.flu-dyn':      'Fluid Dynamics',
        'physics.gen-ph':       'General Physics',
        'physics.geo-ph':       'Geophysics',
        'physics.hist-ph':      'History and Philosophy of Physics',
        'physics.ins-det':      'Instrumentation and Detectors',
        'physics.med-ph':       'Medical Physics',
        'physics.optics':       'Optics',
        'physics.plasm-ph':     'Plasma Physics',
        'physics.soc-ph':       'Social and Information Networks (physics)',
        'physics.space-ph':     'Space Physics',
    },
    "Quantitative Biology": {
        'q-bio.BM':      'Biomolecules',
        'q-bio.CB':      'Cell Behavior',
        'q-bio.GN':      'Genomics',
        'q-bio.MN':      'Molecular Networks',
        'q-bio.NC':      'Neurons and Cognition',
        'q-bio.OT':      'Other Quantitative Biology',
        'q-bio.PE':      'Populations and Evolution',
        'q-bio.QM':      'Quantitative Methods',
        'q-bio.SC':      'Subcellular Processes',
        'q-bio.TO':      'Tissues and Organs',
    },
    "Quantitative Finance": {
        'q-fin.CP':      'Computational Finance',
        'q-fin.EC':      'Economics',
        'q-fin.GN':      'General Finance',
        'q-fin.MF':      'Mathematical Finance',
        'q-fin.PM':      'Portfolio Management',
        'q-fin.PR':      'Pricing of Securities',
        'q-fin.RM':      'Risk Management',
        'q-fin.ST':      'Statistical Finance',
        'q-fin.TR':      'Trading and Market Microstructure',
    },
    "Statistics": {
        'stat.AP':       'Applications',
        'stat.CO':       'Computation',
        'stat.ME':       'Methodology',
        'stat.ML':       'Machine Learning (statistics)',
        'stat.OT':       'Other Statistics',
        'stat.TH':       'Statistics Theory (statistics)',
    },
}
